config/routes.rb
Rails.application.routes.draw do
  get 'about/index', as: :about
  root "home#index"


  resources :starrings
  resources :movies
  resources :actors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/starring.rb
class Starring < ApplicationRecord
  belongs_to :movie
  belongs_to :actor

  enum :role, { lead: 1, support: 2 }, prefix: true

end

app/controllers/starrings_controller.rb
class StarringsController < ApplicationController
  before_action :set_starring, only: %i[ show edit update destroy ]

  # GET /starrings or /starrings.json
  def index
    @starrings = Starring.all
  end

  # GET /starrings/1 or /starrings/1.json
  def show
  end

  # GET /starrings/new
  def new
    @starring = Starring.new
  end

  # GET /starrings/1/edit
  def edit
  end

  # POST /starrings or /starrings.json
  def create
    @starring = Starring.new(starring_params)

    respond_to do |format|
      if @starring.save
        format.html { redirect_to starring_url(@starring), notice: "Starring was successfully created." }
        format.json { render :show, status: :created, location: @starring }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @starring.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /starrings/1 or /starrings/1.json
  def update
    respond_to do |format|
      if @starring.update(starring_params)
        format.html { redirect_to starring_url(@starring), notice: "Starring was successfully updated." }
        format.json { render :show, status: :ok, location: @starring }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @starring.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /starrings/1 or /starrings/1.json
  def destroy
    @starring.destroy

    respond_to do |format|
      format.html { redirect_to starrings_url, notice: "Starring was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_starring
      @starring = Starring.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def starring_params
      params.require(:starring).permit(:movie_id, :actor_id, :role)
    end
end

app/helpers/starrings_helper.rb
module StarringsHelper
end

app/views/starrings/_form.html.erb
<%= form_with(model: starring) do |form| %>
  <% if starring.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(starring.errors.count, "error") %> prohibited this starring from being saved:</h2>

      <ul>
        <% starring.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :movie_id, style: "display: block" %>
    <%= form.text_field :movie_id %>
  </div>

  <div>
    <%= form.label :actor_id, style: "display: block" %>
    <%= form.text_field :actor_id %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.number_field :role %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/starrings/_starring.html.erb
<div id="<%= dom_id starring %>">
  <p>
    <strong>Movie:</strong>
    <%= starring.movie.name %>
  </p>

  <p>
    <strong>Actor:</strong>
    <%= starring.actor.name %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= starring.role %>
  </p>

</div>

app/views/starrings/edit.html.erb
<h1>Editing starring</h1>

<%= render "form", starring: @starring %>

<br>

<div>
  <%= link_to "Show this starring", @starring %> |
  <%= link_to "Back to starrings", starrings_path %>
</div>

app/views/starrings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Starrings</h1>

<div id="starrings">
  <% @starrings.each do |starring| %>
    <%= render starring %>
    <p>
      <%= link_to "Show this starring", starring %>
    </p>
  <% end %>
</div>

<%= link_to "New starring", new_starring_path %>

app/views/starrings/new.html.erb
<h1>New starring</h1>

<%= render "form", starring: @starring %>

<br>

<div>
  <%= link_to "Back to starrings", starrings_path %>
</div>

app/views/starrings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @starring %>

<div>
  <%= link_to "Edit this starring", edit_starring_path(@starring) %> |
  <%= link_to "Back to starrings", starrings_path %>

  <%= button_to "Destroy this starring", @starring, method: :delete %>
</div>