config/routes.rb
Rails.application.routes.draw do
  get 'about/index', as: :about
  root "home#index"


  resources :starrings
  resources :movies
  resources :actors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body id="body" class="">
    <nav class="flex items-center justify-between flex-wrap bg-fuchsia-100 px-6 pt-2 text-pink-400 dark:text-pink-700 shadow shadow-pink-400/30 dark:bg-pink-900 pb-2 lg:pb-0">
      <%= link_to root_path do %><%= svg_tag "ksmovies.svg", alt: "K's Movies", class: "fill-pink-400 dark:fill-pink-700" %><% end %>
      <div class="md:hidden">
        <button class="flex items-center px-2 py-2 text-pink-400 hover:text-white hover:bg-pink-400 rounded" onClick="toggleNavLinks();">
          <%= svg_tag "icon-menu.svg", class: "w-6 fill-pink-400 dark:fill-pink-700" %>
        </button>
      </div>
      <div id="nav-links" class="w-full flex-grow md:flex md:items-center md:w-auto md:block md:visible">
        <%= highlight_link_to "Movies", movies_path, class: "block -mt-2 ml-4 md:inline-block md:ml-8 lg:ml-10 md:mt-0 md:text-base lg:text-lg", active: "pl-1 border-l-4 border-pink-400 md:pl-0 md:border-l-0 md:underline md:underline-offset-8 md:decoration-4 lg:decoration-8" %>
        <%= highlight_link_to "Actors", actors_path, class: "block mt-1  ml-4 md:inline-block md:ml-6 lg:ml-8  md:mt-0 md:text-base lg:text-lg", active: "pl-1 border-l-4 border-pink-400 md:pl-0 md:border-l-0 md:underline md:underline-offset-8 md:decoration-4 lg:decoration-8" %>
        <%= highlight_link_to "Read Me", about_path, class: "block mt-1  ml-4 md:inline-block md:ml-6 lg:ml-8  md:mt-0 md:text-base lg:text-lg", active: "pl-1 border-l-4 border-pink-400 md:pl-0 md:border-l-0 md:underline md:underline-offset-8 md:decoration-4 lg:decoration-8" %>
        <%= highlight_link_to "Settings", "TODO",    class: "block mt-1  ml-4 md:hidden",   active: "pl-1 border-l-4 border-pink-400" %>
      </div>
      <div class="hidden md:inline-block ml-4">
        <%= link_to "TODO" do %>
          <%= svg_tag "icon-cog.svg", class: "w-6 fill-pink-400 dark:fill-pink-700" %>
        <% end %>
      </div>
    </nav>
    <main class="p-4 mx-auto bg-fuchsia-50 dark:bg-neutral-900 h-screen">
      <%= yield %>
    </main>
  </body>
  <script>
  // if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
  //  document.documentElement.classList.add('dark')
  // }
  // else {
  //   document.documentElement.classList.remove('dark')
  // }
  </script>
</html>